name: dog_breed_app
description: "Dog Breed app with BloC state management in Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueBlack.ttf
          weight: 900
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueBold.ttf
          weight: 700
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueLight.ttf
          weight: 200
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueRegular.ttf